string $objs[] = `ls -sl`;
string $buffer[]; 
string $tempName ;

    for($i = 0; $i < size($objs); $i++)
        {
        clear $buffer; 
        tokenize $objs[$i] "_" $buffer; 
        $tempName = $buffer[0];
        circle -n ($tempName + ($i + 1))  ;
        doGroup 0 1 1; 
        rename ($tempName + ($i + 1) + "_Grp");
        matchTransform ($tempName + ($i + 1) + "_Grp") $objs[$i];
        }
        
    for($i = 0; $i < size($objs); $i++)
    {
        
    }